%usepalette current
# Scheme: ${scheme}
# Author: ${author}
[colors.primary]
background = "#${base00}"
foreground = "#${base05}"

[colors.selection]
text = "CellForeground"
background = "#${base02}"

[colors.cursor]
text = "#${base00}"
cursor = "#${base05}"

[colors.vi_mode_cursor]
text = "#${base00}"
cursor = "#${base05}"

[colors.normal]
black = "#${base02}"
red = "#${base08}"
green = "#${base0B}"
yellow = "#${base0A}"
blue = "#${base0D}"
magenta = "#${base0E}"
cyan = "#${base0C}"
white = "#${base05}"
%endpalette current
%usepalette current-light

[colors.bright]
black = "#${base03}"
red = "#${base08}"
green = "#${base0B}"
yellow = "#${base0A}"
blue = "#${base0D}"
magenta = "#${base0E}"
cyan = "#${base0C}"
white = "#${base07}"
%endpalette current-light
